using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TabbedPageWithNavigationPage
{
    /// <summary>
    /// Interaction logic for start.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class start : ContentPage
    {
        public start()
        {
            InitializeComponent();
        }
    }
}
	