using System;
using System.Collections.Generic;
using TabbedPageWithNavigationPage.Models;
using Xamarin.Forms;
using System.Linq;

namespace TabbedPageWithNavigationPage
{
    /// <summary>
    /// Interaction logic for user_profile.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class user_profile : ContentPage
    {
        public user_profile()
        {
            InitializeComponent();
        }
    }
}
	